Repository vaadin/vaadin-overlay, pull requests merged in 2018-09, with the labels that each got.

#120 Call render when overlay first time opened
  demo/index.html
  src/vaadin-overlay.html
  test/renderer.html
Labels: in review unscoped

#121 Enable visual tests
  .gemini.yml
  .travis.yml
  test/visual/default.html
  test/visual/screens/vaadin-overlay/default-tests-lumo/default/chrome.png
  test/visual/screens/vaadin-overlay/default-tests-lumo/default/firefox.png
  test/visual/screens/vaadin-overlay/default-tests-material/default/chrome.png
  test/visual/screens/vaadin-overlay/default-tests-material/default/firefox.png
  test/visual/test.js
Labels: in review unscoped

#124 Fix re-opening before closing animation end and vice versa
  src/vaadin-overlay.html
  test/animations.html
  test/test-suites.js
Labels: in review

#126 Fix tabbable nodes collection to be not Polymer specific
  bower.json
  src/vaadin-focusables-helper.html
  src/vaadin-overlay.html
  test/animations.html
  test/focus-trap.html
Labels: in review

#127 Improve renderers docs [skip ci]
  src/vaadin-overlay.html
Labels: in progress
